<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Device.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Device.Domain\Device.Domain.csproj" />
    <ProjectReference Include="..\EFCore.Infrastructure\EFCore.Infrastructure.csproj" />
  </ItemGroup>

</Project>
