<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework.Core\Framework.Core.csproj" />
    <ProjectReference Include="..\Log.Domain\Serilog.Domain.csproj" />
    <ProjectReference Include="..\PrismUI.Core\PrismUI.Core.csproj" />
    <ProjectReference Include="..\SemiControl_Net\SemiControl_Net.csproj" />
  </ItemGroup>

</Project>
