<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework.Imaging\Framework.Imaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YoloDotNet" Version="4.2.0" />
    <PackageReference Include="YoloDotNet.ExecutionProvider.Cpu" Version="1.1.0" />
  </ItemGroup>

</Project>
