<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Baksteen.Extensions.DeepCopy" Version="1.0.5" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCore.Infrastructure\EFCore.Infrastructure.csproj" />
    <ProjectReference Include="..\Framework.Core\Framework.Core.csproj" />
    <ProjectReference Include="..\Recipe.Domain\Recipe.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
