// <auto-generated />
using System;
using Framework.Device.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Framework.Device.Infrastructure.Migrations
{
    [DbContext(typeof(DeviceDataContext))]
    partial class DeviceDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Framework.Device.Domain.Entity.DeviceConfigurationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("设备逻辑标识（主键）");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeviceConfiguration", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "CameraA",
                            ConnectionType = 1,
                            IpAddress = "192.168.1.64",
                            Kind = 1,
                            Port = 8000,
                            Vendor = "HikVision"
                        },
                        new
                        {
                            Id = "MotionCard1",
                            ConnectionType = 2,
                            Kind = 2,
                            PortName = "COM1",
                            Vendor = "Leisai"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
