<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="RecipeUI\excel-5.png" />
    <None Remove="RecipeUI\folder-3.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Recipe.Infrastructure\Recipe.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="RecipeUI\excel-5.png" />
    <Resource Include="RecipeUI\folder-3.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework.Core\Framework.Core.csproj" />
    <ProjectReference Include="..\PrismUI.Core\PrismUI.Core.csproj" />
    <ProjectReference Include="..\Recipe.Domain\Recipe.Domain.csproj" />
    <ProjectReference Include="..\SemiControl_Net\SemiControl_Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="RecipeUI\RecipeHomeView.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
