<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UI.FrameWork.Core\UI.FrameWork.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Language\" />
    <Folder Include="UI.FrameWork.Core\Common\" />
  </ItemGroup>

</Project>
