// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipe.Domain;

#nullable disable

namespace Recipe.Domain.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260704084814_Update03")]
    partial class Update03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Recipe.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Data unique identifier.");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            GroupName = "-Default-",
                            MachineName = "ZS1A",
                            RecipeName = "default"
                        });
                });

            modelBuilder.Entity("Recipe.Domain.RecipeManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRecipeId");

                    b.ToTable("RecipeManager", t =>
                        {
                            t.HasCheckConstraint("CK_RecipeManager_SingleRow", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentRecipeId = -1
                        });
                });

            modelBuilder.Entity("Recipe.Domain.RecipeParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Data unique identifier.");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeParameter");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Recipe.Domain.CameraConfiguration", b =>
                {
                    b.HasBaseType("Recipe.Domain.RecipeParameter");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("CameraConfiguration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecipeId = -1,
                            CameraName = "CameraA"
                        },
                        new
                        {
                            Id = 2,
                            RecipeId = -1,
                            CameraName = "CameraB"
                        },
                        new
                        {
                            Id = 3,
                            RecipeId = -1,
                            CameraName = "CameraC"
                        },
                        new
                        {
                            Id = 4,
                            RecipeId = -1,
                            CameraName = "CameraD"
                        });
                });

            modelBuilder.Entity("Recipe.Domain.RecipeManager", b =>
                {
                    b.HasOne("Recipe.Domain.Recipe", "CurrentRecipe")
                        .WithMany()
                        .HasForeignKey("CurrentRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentRecipe");
                });

            modelBuilder.Entity("Recipe.Domain.RecipeParameter", b =>
                {
                    b.HasOne("Recipe.Domain.Recipe", "Recipe")
                        .WithMany("Parameters")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Recipe.Domain.Recipe", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
