// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipe.Domain;

#nullable disable

namespace Recipe.Domain.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Recipe.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Data unique identifier.");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            GroupName = "-Default-",
                            MachineName = "ZS1A",
                            RecipeName = "default"
                        });
                });

            modelBuilder.Entity("Recipe.Domain.RecipeParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasComment("Data unique identifier.");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeParameter");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Recipe.Domain.CameraConfiguration", b =>
                {
                    b.HasBaseType("Recipe.Domain.RecipeParameter");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("CameraConfiguration");
                });

            modelBuilder.Entity("Recipe.Domain.RecipeParameter", b =>
                {
                    b.HasOne("Recipe.Domain.Recipe", "Recipe")
                        .WithMany("Parameters")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Recipe.Domain.Recipe", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
